/**
 * Draw-tab palette: the official NWCG PMS 936 symbology (../nwcg, generated by
 * scripts/nwcg_symbology.py) — NWCG's own Event Point icons and every Event
 * Line / Perimeter Line style from NIFC's layer files — plus two app extras
 * that are not in PMS 936: the orange Sketch pen and Wildfire Perimeter.
 */
import {
  NWCG_LINE_CATEGORIES,
  NWCG_LINES,
  NWCG_POINT_CATEGORIES,
  NWCG_POINTS,
  type NwcgLineStyle,
  type NwcgPointSymbol,
} from '../nwcg/symbology.gen';

/** The official PNGs (small enough that Vite inlines them into the bundle). */
const ICON_URLS = import.meta.glob<string>('../nwcg/points/*.png', {
  eager: true,
  import: 'default',
});

export interface DrawSymbol extends NwcgPointSymbol {
  url: string;
}

export type DrawLineStyle = NwcgLineStyle;

export const DRAW_SYMBOLS: DrawSymbol[] = NWCG_POINTS.map((p) => ({
  ...p,
  url: ICON_URLS[`../nwcg/points/${p.id}.png`],
}));

/** Not part of PMS 936 — kept beside the official lines. */
export const DRAW_LINE_EXTRAS: DrawLineStyle[] = [
  {
    id: 'sketch',
    label: 'Sketch',
    category: '',
    parts: [{ kind: 'stroke', color: '#ffbd5a', width: 2.25, cap: 'round', join: 'round' }],
  },
  {
    id: 'perimeter',
    label: 'Wildfire Perimeter',
    category: '',
    parts: [{ kind: 'stroke', color: '#cc0000', width: 3, cap: 'round', join: 'round' }],
  },
];

export const DRAW_LINES: DrawLineStyle[] = [...DRAW_LINE_EXTRAS, ...NWCG_LINES];

/** Palette sections, in the layer files' legend order. */
export const DRAW_SYMBOL_GROUPS = NWCG_POINT_CATEGORIES.map((category) => ({
  category,
  items: DRAW_SYMBOLS.filter((s) => s.category === category),
}));

export const DRAW_LINE_GROUPS = NWCG_LINE_CATEGORIES.map((category) => ({
  category,
  items: NWCG_LINES.filter((l) => l.category === category),
}));

// Ids that marks saved before the NWCG palette still carry (localStorage).
const LEGACY_SYMBOL_IDS: Record<string, string> = {
  division: 'division-break',
  branch: 'branch-break',
  airstrip: 'airstrip-or-airport',
  uas: 'uas-launch-and-recovery',
  drop: 'drop-point',
  staging: 'staging-area',
  dip: 'dip-site',
  wxunit: 'mobile-weather-unit',
  risk: 'value-at-risk',
  firestation: 'fire-station',
};
const LEGACY_LINE_IDS: Record<string, string> = {
  dozer: 'completed-dozer-line',
  fuelbreak: 'completed-fuel-break',
  handline: 'completed-hand-line',
  mixedline: 'completed-mixed-construction-line',
  roadline: 'completed-road-as-line',
  aviation: 'aviation-route',
  contained: 'contained-fire-edge',
};

const SYMBOL_BY_ID = new Map(DRAW_SYMBOLS.map((s) => [s.id, s]));
const LINE_BY_ID = new Map(DRAW_LINES.map((l) => [l.id, l]));

export function drawSymbolById(id: string | undefined): DrawSymbol | undefined {
  return id ? SYMBOL_BY_ID.get(LEGACY_SYMBOL_IDS[id] ?? id) : undefined;
}

export function drawLineById(id: string | undefined): DrawLineStyle | undefined {
  return id ? LINE_BY_ID.get(LEGACY_LINE_IDS[id] ?? id) : undefined;
}
