/**
 * Post-build service worker generator (run by `npm run build` after vite).
 *
 * Deliberately minimal and rollback-safe:
 *  - navigations are NETWORK-FIRST (every online load picks up new deploys;
 *    reverting main reaches every client on their next load), falling back to
 *    the cached index.html only when offline;
 *  - only same-origin static assets are cached (content-hashed /assets plus
 *    the small fixed set below), cache-first since their names change per build;
 *  - the cache name embeds a content hash, and activate deletes every other
 *    cache — deploying anything (including a revert) replaces the shell.
 * Data (B2, fire-api) is NEVER touched here — offline data lives in OPFS
 * packs handled by the app itself.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dist = new URL('../dist', import.meta.url).pathname;

function walk(dir, prefix) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p, `${prefix}${name}/`));
    else out.push(`${prefix}${name}`);
  }
  return out;
}

// Derive the deploy base from the built index.html (vite rebases its asset
// URLs) so the SW works at '/' AND under a project-page base — and never
// silently mismatches the build it ships with.
const indexHtml = readFileSync(join(dist, 'index.html'), 'utf8');
const baseMatch = /(?:src|href)="([^"]*)\/assets\//.exec(indexHtml);
const base = baseMatch ? baseMatch[1] : '';
const entryChunk = /\/assets\/(index-[^"]+\.js)"/.exec(indexHtml)?.[1];
if (!entryChunk) throw new Error('build-sw: entry chunk not found in index.html');

const assets = [
  `${base}/index.html`,
  `${base}/manifest.webmanifest`,
  `${base}/favicon.svg`,
  ...walk(join(dist, 'assets'), `${base}/assets/`),
  ...walk(join(dist, 'fonts'), `${base}/fonts/`),
  ...walk(join(dist, 'icons'), `${base}/icons/`),
];

const hash = createHash('sha256');
for (const a of assets) {
  hash.update(a);
  hash.update(readFileSync(join(dist, a.slice(base.length + 1))));
}
const version = `rd-shell-${hash.digest('hex').slice(0, 12)}`;

const sw = `/* generated by scripts/build-sw.mjs — do not edit */
const VERSION = ${JSON.stringify(version)};
const ASSETS = ${JSON.stringify(assets)};
const ASSET_SET = new Set(ASSETS);
const INDEX = ${JSON.stringify(`${base}/index.html`)};
const ENTRY_CHUNK = ${JSON.stringify(entryChunk)};

self.addEventListener('install', (e) => {
  e.waitUntil(
    (async () => {
      const c = await caches.open(VERSION);
      // cache: 'reload' bypasses the HTTP cache — an install must never pair
      // a stale cached index.html with this build's assets. The entry-chunk
      // check also catches CDN skew (old index still propagating): failing
      // install here just retries on a later load, which is the safe outcome.
      await c.addAll(ASSETS.map((a) => new Request(a, { cache: 'reload' })));
      const idx = await (await c.match(INDEX)).text();
      if (!idx.includes(ENTRY_CHUNK)) {
        throw new Error('index.html/assets skew — retrying next load');
      }
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match(INDEX)));
    return;
  }
  if (ASSET_SET.has(url.pathname)) {
    e.respondWith(caches.match(url.pathname).then((hit) => hit || fetch(req)));
  }
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`sw.js: ${assets.length} precached assets, version ${version}`);
