/**
 * Post-build service worker generator (run by `npm run build` after vite).
 *
 * Deliberately minimal and rollback-safe:
 *  - navigations are NETWORK-FIRST (every online load picks up new deploys;
 *    reverting main reaches every client on their next load), falling back to
 *    the cached index.html only when offline;
 *  - only same-origin static assets are cached (content-hashed /assets plus
 *    the small fixed set below), cache-first since their names change per build;
 *  - the cache name embeds a content hash, and activate deletes every other
 *    cache — deploying anything (including a revert) replaces the shell.
 * Data (B2, fire-api) is NEVER touched here — offline data lives in OPFS
 * packs handled by the app itself.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dist = new URL('../dist', import.meta.url).pathname;

function walk(dir, prefix) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p, `${prefix}${name}/`));
    else out.push(`${prefix}${name}`);
  }
  return out;
}

const assets = [
  '/index.html',
  '/manifest.webmanifest',
  '/favicon.svg',
  ...walk(join(dist, 'assets'), '/assets/'),
  ...walk(join(dist, 'fonts'), '/fonts/'),
  ...walk(join(dist, 'icons'), '/icons/'),
];

const hash = createHash('sha256');
for (const a of assets) {
  hash.update(a);
  hash.update(readFileSync(join(dist, a.slice(1))));
}
const version = `rd-shell-${hash.digest('hex').slice(0, 12)}`;

const sw = `/* generated by scripts/build-sw.mjs — do not edit */
const VERSION = ${JSON.stringify(version)};
const ASSETS = ${JSON.stringify(assets)};
const ASSET_SET = new Set(ASSETS);

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(VERSION).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('/index.html')));
    return;
  }
  if (ASSET_SET.has(url.pathname)) {
    e.respondWith(caches.match(url.pathname).then((hit) => hit || fetch(req)));
  }
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`sw.js: ${assets.length} precached assets, version ${version}`);
